# Generated by Django 3.2.7 on 2022-01-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_applyloanplan'),
        ('users', '0009_auto_20211008_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_origin_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loan_subscription_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loan_subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.applyloanplan'),
        ),
    ]
