# Generated by Django 3.2.7 on 2022-01-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220101_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_subscription_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
