# Generated by Django 3.2.7 on 2022-01-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_loan_subscription_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_subscription_added_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
