# Generated by Django 3.2.7 on 2022-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_productpurchasedmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyLoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.CharField(blank=True, max_length=120, null=True)),
                ('subscription_stripe_id', models.CharField(max_length=150)),
                ('origin_fee_stripe_id', models.CharField(max_length=150)),
            ],
        ),
    ]
