# Generated by Django 3.2.7 on 2022-01-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_applyloanplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloanplan',
            name='origin_fee',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
