# Generated by Django 3.2.7 on 2022-01-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_applyloanplan_origin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloanplan',
            name='aproved_loan_amount',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
