# Generated by Django 3.2.7 on 2022-01-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_applyloanplan_aproved_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyloanplan',
            name='duration',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
